import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Beneficiary Management System",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/saylani-logo.png" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <Toaster richColors position="top-center" />
        {children}
      </body>
    </html>
  );
}
